before:
  hooks:
    - make clean
builds:
  - main: ./cmd/git-semv
    env:
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
github:
  owner: linyows
  name: homebrew-git-semv
description: This is a Git plugin for Semantic Versioning.
homepage: https://github.com/linyows/git-semv
install: |
  bin.install Dir['git-semv']
  #  zsh_completion.install "misc/completion.zsh"
  #  bash_completion.install "misc/completion.bash"
  #  fish_completion.install "misc/completion.fish"
test: |
  system "#{bin}/git-semv"
